# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: 'android'
    gradleWrapperFile: 'android/gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'

- task: AndroidSigning@3
  inputs:
    apkFiles: 'android/app/build/outputs/apk/release/*.apk'
    apksignerKeystoreFile: 'my-release-key.keystore'
    apksignerKeystorePassword: '$(KeystorePassword)'
    apksignerKeystoreAlias: 'alias_name'
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'android/app/build/outputs/apk'
    ArtifactName: 'drop'
    publishLocation: 'Container'



#- task: GitHubRelease@1
#  inputs:
#    gitHubConnection: 'github'
#    repositoryName: '$(Build.Repository.Name)'
#    action: 'create'
#    target: '$(Build.SourceVersion)'
#    tagSource: 'gitTag'
#    assets: 'android/app/build/outputs/apk/*.apk'
#    changeLogCompareToRelease: 'lastFullRelease'
#    changeLogType: 'commitBased'