FROM golang:alpine AS build

WORKDIR /app
ENV CGO_ENABLED=1

RUN apk add --no-cache \
    # Important: required for go-sqlite3
    gcc \
    # Required for Alpine
    musl-dev

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY smsq/*.* ./

RUN GOOS=linux GOARCH=amd64 go build -o /smsq-backend


FROM alpine:latest

WORKDIR /

COPY --from=build /app/pk.json /
COPY --from=build /app/config.json /
COPY --from=build /smsq-backend /
RUN apk add --no-cache libc6-compat
RUN apk add --no-cache gcompat

EXPOSE 80


CMD ["./smsq-backend", "config.json" ]